### ISSUE TITLE
glualint doesn't work with vanilla Lua language id?

### ISSUE THREAD

**Issue by Tenrys** [Goz3rr/vscode-glualint#1]
I can't get this to lint default Lua. I like to disable the glua extension when not working with GLua files, and it seems this extension doesn't run glualint on normal Lua files at all, even though the config says it should.

**Comment by Goz3rr** [comment]
Yup it seems to stop working for lua when the glua extension is disabled, I'll have a look at it

**Comment by Goz3rr** [comment]
I've published a new version which should work even without a `glua` language installed

**Comment by Tenrys** [comment]
Nice, thanks for the fast reply and fix.
