### ISSUE TITLE
Hide Warnings / Confused (VSCode)

### ISSUE THREAD

**Issue by d4kir92** [Goz3rr/vscode-glualint#12]
How can i hide specific warnings that i dont need?

and

how can i fix this warning?
![image](https://user-images.githubusercontent.com/23246564/231373395-429b4a73-3d27-449d-a24c-5843a7ec15f4.png)

local delay = 0.01

and

is it possible to use tabs instead of 4 spaces?

**Comment by Goz3rr** [comment]
The first two questions are both answered [here](https://github.com/FPtje/GLuaFixer/blob/master/README.md#configuring-glualint)

Pretty printing should use whatever your vscode is set to, in the bottom right of the status bar you can choose between tabs or spaces.
