### ISSUE TITLE
Failed formatting the file

### ISSUE THREAD

**Issue by ZehMatt** [Goz3rr/vscode-glualint#14]
I just get an error `Failed to pretty print code, most likely due to syntax errors`. I have the latest version of this extension and glualint is at the version 1.25.0

Running glualint from the command line on the same file has no errors so I'm guessing it is rather the extension than glualint.

**Comment by Goz3rr** [comment]
I've left a comment on the PR as well, but for posterity:

You're probably running the "Format Selection" with no selection, so glualint returns an empty string which makes the extension think it failed. vscode provides a "Format Document" action as well which formats the entire document.

**Comment by ZehMatt** [comment]
My bad, not an actual issue.
