### ISSUE TITLE
Issue when trying to pretty print

### ISSUE THREAD

**Issue by SenseiHiraku** [Goz3rr/vscode-glualint#2]
The Pretty Print feature does not seeming to work.
When I type "glualint --version" in the Terminal it returns the Version, but when I try to Pretty Print, it does not seems to return anything and the terminal is freezing.

**Comment by Goz3rr** [comment]
So my extension didn't really support pretty printing, just showing the linting results. By manually invoking the linter with --pretty-print it was waiting for input and making it seem as if the terminal was frozen.

I've just pushed version 0.4.0 which has added pretty printing support (vscode's default shortcuts are Shift+Alt+F to format the entire document and Ctrl+K, Ctrl+F to format the current selection or just type format into the command palette).

Let me know if it works for you.

For future reference, when using my extension you shouldn't have to manually call glualint from the terminal. In fact when doing so it completely bypasses my extension.
