### ISSUE TITLE
Disable Warnings

### ISSUE THREAD

**Issue by t3r00t** [Goz3rr/vscode-glualint#5]
### Hello !

All my projects have a lot of annoying Warnings about spacing and tabs, whitespaces and such
All of theses are useless since all my code is compressed and Obfuscated before release...

A simple _"glualint.disableWarnings":True_ would be *perfect* !

If a VSCode built-in solution exist can you please point me to the right place to do this thanks 👍 

##### T3R00T

**Comment by Goz3rr** [comment]
Hey!

I'm not really sure what you're asking for, I could add something like `glualint.disableWarnings` but that would effectively disable the entire extension? Normally I'd imagine you keep a non compressed file that you use for development, it's to be expected that a minified version gives style warnings.

I think you might be able to find what you want in the [glualint configuration](https://github.com/FPtje/GLuaFixer/blob/master/README.md#configuring-glualint) section. Simply place a `glualint.json` in your project folder, and have a look at options like `lint_whitespaceStyle` or `lint_ignoreFiles`
