### ISSUE TITLE
Entire document gets nuked if prettyprint_rejectInvalidCode is set to True

### ISSUE THREAD

**Issue by ExtReMLapin** [Goz3rr/vscode-glualint#6]
The issue is you can make glualint pretty print on saving, but if you got a syntax error it will just fuck up your code, so I decided to disable pretty print on syntax error, but now it just nukes the code (empties the current document)

**Comment by Goz3rr** [comment]
I've just published version 0.6.0 which should no longer wipe the file if pretty printing fails.
