### ISSUE TITLE
Cannot find glualint when using SSH

### ISSUE THREAD

**Issue by TheOnly8Z** [Goz3rr/vscode-glualint#7]
I am connecting to a windows 10 server using VS Code's SSH plugin. Despite the PATH environment being set and reloading the window, the plugin still cannot find glualint.exe.
![image](https://user-images.githubusercontent.com/13565172/107366783-7bc82200-6b19-11eb-898f-ba950f37a590.png)
![image](https://user-images.githubusercontent.com/13565172/107366797-7f5ba900-6b19-11eb-9213-2c8188fe764f.png)
![image](https://user-images.githubusercontent.com/13565172/107366810-8387c680-6b19-11eb-87ef-f2941346cf2e.png)

**Comment by Goz3rr** [comment]
Please try checking using the terminal inside vscode (can be opened with ctrl+\` or View -> Terminal), if the PATH is correctly set there, and if you can execute the `glualint` command. The glualint executable has to be available on the same machine as where vcsode is running. I've sometimes seen some strange cases where vscode does not update the PATH at all for some reason, a reboot might help as well.

If that fails, you can also try changing the `glualint.linter` setting from `glualint` to `E:/glualint/glualint.exe` in your case, then it shouldn't matter what the PATH is set to.

**Comment by TheOnly8Z** [comment]
Changing the linter setting solved this issue, thanks.
