### ISSUE TITLE
Linting in VS Code Git diff window not following glualint.json settings

### ISSUE THREAD

**Issue by Malivil** [Goz3rr/vscode-glualint#8]
Hi,

I'm using your extension while working on some GMod addons and I'm really liking it
One thing I've noticed, though, is that when I look at the diff between files using the standard Git diff window on the Source Control tab, it doesn't appear to follow the glualint.json settings

For example, I open a file to edit it and there are no warnings. I then look at the diff on the Source Control tab before committing and it shows a bunch of warnings for things I have disabled in my glualint.json

Let me know if you need more information from me =)
Thanks in advance

**Comment by Goz3rr** [comment]
Hey!

If I'm understanding right, you have some code like this:
```lua
function foo(a)
    print(a+1)
end

function bar()
    print(self)
end
```

Which would normally result in two warnings with the default config, but a glualint.json in the same folder to disable some:
```json
{
    "lint_whitespaceStyle": false
}
```

With this example it seems to work fine for me, both in the regular editor:
![image](https://user-images.githubusercontent.com/761433/134583006-46ce0401-7133-4110-b7be-efcc697cee0b.png)

and the diff:
![image](https://user-images.githubusercontent.com/761433/134583021-e4308ee4-21c6-403f-90f5-b2d4e840a8dd.png)

Do you have some other example I can reproduce it with?

I noticed one small oversight in the code where it would not correctly set the working directory, but this shouldn't cause a difference between text mode and git mode.

I'm not sure what exactly could be going wrong, as my extension basically doesn't handle the configuration part at all. This is all handled by glualint itself, as [documented here](https://github.com/FPtje/GLuaFixer#configuring-glualint). It will try to find a glualint.json in the current folder of your project, all the way to the root of the drive. If none is found there it will try for a .glualint.json in your home folder. I could add support for the `--config` parameter as well but that's not really related either.

**Comment by Malivil** [comment]
Hi!

Thanks for getting back to me. I got a a couple screenshots to show what's happening on my side and it might only be happening on the "old" side of the diff which wouldn't happen in your example.

Here's what it looks like in the live file:
![Live](https://user-images.githubusercontent.com/1238511/134592847-11f9a1c4-f208-4aca-becf-f092018edcf7.jpg)

Versus what it looks like in the diff:
![Diff](https://user-images.githubusercontent.com/1238511/134592868-68ad91d2-3d20-4ca0-8fa6-bca99b95d09a.jpg)

You can see on left of the diff there are sections underlined based on a setting I have disabled

**Comment by Goz3rr** [comment]
Gotcha, I see what you mean now. I managed to reproduce it and just put out version 0.7.0 which should fix your issue.

**Comment by Malivil** [comment]
I can verify it is fixed.

Thanks a lot for the quick turnaround =)
